name: Changesets
on:
  ## Allow triggering this workflow manually via GitHub CLI/web
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node and dependencies
        uses: ./.github/actions/install-dependencies
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: pnpm changeset-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
