name: Changesets
on:
  ## Allow triggering this workflow manually via GitHub CLI/web
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node and dependencies
        uses: ./.github/actions/install-dependencies
      - name: Create Release Pull Request
        uses: changesets/action@f13b1baaa620fde937751f5d2c3572b9da32af23 # pin@v1
        with:
          # Generates src/version.ts file using genVersion
          # https://github.com/changesets/action#with-version-script
          version: pnpm changeset-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
